---
title: 'Reproducible Research: Peer Assessment 1'
output: md_document
    
editor_options: 
  chunk_output_type: console
---


## Loading and preprocessing the data

```{r}
setwd("C:/Users/John/Desktop/repData")
library(knitr)
library(rmarkdown)
library(data.table)
library(ggplot2)
library(DescTools)
library(png)

```
## Reading csv Data into Data.Table. 
```{r}
activityDT <- data.table::fread(input = "activity.csv")

```

## What is mean total number of steps taken per day?



```{r echo=FALSE}
Total_Steps <- activityDT[, c(lapply(.SD, sum, na.rm = FALSE)), .SDcols = c("steps"), by = .(date)] 
head(Total_Steps, 10)
```



```{r, echo=FALSE,results='hide',fig.keep='all'}
ggplot(Total_Steps, aes(x = steps)) +
    geom_histogram(fill = "blue", binwidth = 1000) +
    labs(title = "Daily Steps", x = "Steps", y = "Frequency")

```


```{r, echo=FALSE,results='hide',fig.keep='all'}
Total_Steps[, .(Mean_Steps = mean(steps, na.rm = TRUE), Median_Steps = median(steps, na.rm = TRUE))]
```

## What is the average daily activity pattern?


```{r, echo=FALSE,results='hide',fig.keep='all'}
IntervalDT <- activityDT[, c(lapply(.SD, mean, na.rm = TRUE)), .SDcols = c("steps"), by = .(interval)] 
ggplot(IntervalDT, aes(x = interval , y = steps)) + geom_line(color="blue", size=1) + labs(title = "Avg. Daily Steps", x = "Interval", y = "Avg. Steps per day")
```



```{r echo=FALSE}
IntervalDT[steps == max(steps), .(max_interval = interval)]
```


## Imputing missing values



```{r echo=FALSE}
activityDT[is.na(steps), .N ]
# alternative solution
nrow(activityDT[is.na(steps),])
```


```{r echo=FALSE}
# Filling in missing values with median of dataset. 
activityDT[is.na(steps), "steps"] <- activityDT[, c(lapply(.SD, median, na.rm = TRUE)), .SDcols = c("steps")]
```



```{r echo=FALSE}
data.table::fwrite(x = activityDT, file = "tidyData.csv", quote = FALSE)
```



```{r, echo=FALSE,results='hide',fig.keep='all'}
# total number of steps taken per day
Total_Steps <- activityDT[, c(lapply(.SD, sum)), .SDcols = c("steps"), by = .(date)] 
# mean and median total number of steps taken per day
Total_Steps[, .(Mean_Steps = mean(steps), Median_Steps = median(steps))]
ggplot(Total_Steps, aes(x = steps)) + geom_histogram(fill = "blue", binwidth = 1000) + labs(title = "Daily Steps", x = "Steps", y = "Frequency")
```

Type of Estimate | Mean_Steps | Median_Steps
--- | --- | ---
First Part (with na) | 10765 | 10765
Second Part (fillin in na with median) | 9354.23 | 10395

## Are there differences in activity patterns between weekdays and weekends?

```{r, echo=FALSE,results='hide',fig.keep='all'}

activityDT <- data.table::fread(input = "activity.csv")
activityDT[, date := as.POSIXct(date, format = "%Y-%m-%d")]
activityDT[, `Day of Week`:= weekdays(x = date)]
activityDT[grepl(pattern = "Monday|Tuesday|Wednesday|Thursday|Friday", x = `Day of Week`), "weekday or weekend"] <- "weekday"
activityDT[grepl(pattern = "Saturday|Sunday", x = `Day of Week`), "weekday or weekend"] <- "weekend"
activityDT[, `weekday or weekend` := as.factor(`weekday or weekend`)]
head(activityDT, 10)
```



```{r, echo=FALSE,results='hide',fig.keep='all'}
activityDT[is.na(steps), "steps"] <- activityDT[, c(lapply(.SD, median, na.rm = TRUE)), .SDcols = c("steps")]
IntervalDT <- activityDT[, c(lapply(.SD, mean, na.rm = TRUE)), .SDcols = c("steps"), by = .(interval, `weekday or weekend`)] 
ggplot(IntervalDT , aes(x = interval , y = steps, color=`weekday or weekend`)) + geom_line() + labs(title = "Avg. Daily Steps by Weektype", x = "Interval", y = "No. of Steps") + facet_wrap(~`weekday or weekend` , ncol = 1, nrow=2)
```